### ISSUE TITLE
Not sure if base option is working

### ISSUE THREAD

**Issue by kevinohara80** [Two-Screen/grunt-zipstream#4]
Here is my directory structure of the files that I am trying to zip.

```
/tmp
  /js
    /myfile.js
    /myfile.min.js
  /css
    /mycss.css
    /mycss.min.css
```

I am trying to strip the `tmp` folder from the resulting zip file and I am assuming that this is what the `base` options is. However, the `tmp` folder is always the top-level directory when I zip up the files. Here is my zip task in my Gruntfile.

``` js
zip: {
  build: {
    src: ['tmp/**/*'],
    dest: 'build/staticresources/<%= pkg.name %>.zip',
    base: 'tmp'
  }
}
```

It's possible that I just don't know what the base options is supposed to be doing. Let me know if I am using is correctly or if this is an issue that needs to be fixed. If there is another way to strip this top-level directory please let me know.

**Comment by stephank** [comment]
You want the following:

```
zip: {
  build: {
    src: ['tmp/**/*'],
    dest: 'build/staticresources/<%= pkg.name %>.zip',
    options: {
      base: 'tmp/'
    }
  }
}
```

The trailing slash in `base` is important, because it's a simple string operation. So with `tmp`, it'd end up creating absolute paths like `/js/myfile.js`, whereas you probably want `tmp/` giving you relative paths like `js/myfile.js`.

There was a bug in 0.2.1 that causes `tmp/**/*` to zip your files twice, btw. I published 0.2.2 to fix this. But you can also simply say `tmp` now.

If this doesn't fix you problem, feel free to reopen. :)

**Comment by stephank** [comment]
Noticed this was a documentation issue too, so I updated the README just now. Thanks for reporting!

**Comment by kevinohara80** [comment]
No problem. The plugin works great now. Thanks for fixing!

**Comment by kevinohara80** [comment]
I'm having an issue with this again. I have this....

``` js
ltv: {
  options: {
    base: 'tmp/ltv/'
  },
  src: ['tmp/ltv/**/*'],
  dest: 'tmp/ltv.zip'
}
```

My zip file contains `ltv` as the top-level directory. I am trying to strip `tmp/ltv/` using the base options.

**Comment by kevinohara80** [comment]
Bah, nevermind. User error. Working fine ;)
